### ISSUE TITLE
General request: How to disable autoupdate with server restart?

### ISSUE THREAD

**Issue by drphlux** [alinmear/docker-conanexiles#13]
Hi.
My dedicated server is running fine, but sometimes there are a lot of
unscheduled crashes/restarts. I've been going trough the server logs
in retrospect, and I just found out that these restarts are because of
autoupdates of Conan. Ref:

```
Info: New build available. Updating 2765854 -> 2783891
2018-05-18 11:02:54,728 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-20 05:17:53,703 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-20 14:03:13,261 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-21 22:46:16,150 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-22 01:09:42,825 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-22 23:18:12,763 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-24 06:50:18,322 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 ->
2018-05-24 21:01:55,758 INFO waiting for conanexilesServer to stop
--
Info: New build available. Updating 2783891 -> 2804283
2018-05-25 13:30:55,489 INFO waiting for conanexilesServer to stop
```

What is the simplest way of doing these restarts more controlled?

**Comment by drphlux** [comment]
I didn't want to mess too much with your scripts, so I just changed 
the sleep timer in the main loop in conanexiles_controller.sh.

I will wait for rcon support, that can warn the players to log out
a few minutes before the server actually restarts: #11 

I compiled and tried https://github.com/n0la/rcon but I couldn't make 
it work properly on centos 7. 
mcrcon did work though.

**Comment by alinmear** [comment]
Hm this seems like a bug; the first line of your logs is ok:
```
Info: New build available. Updating 2765854 -> 2783891
```
but the other lines are not. The logic within the container is:
1. Controller checks if there is a new version via steamcmd
2. If yes, shutdown server and do update
3. After update start server again

So there is a missbehaviour with checking installed version against new version

**Comment by alinmear** [comment]
Can you verify, that this behavior is still existing, otherwise we have rework the update check logic and why this is happening. 

3 things could be the cause of this behavior:

1. actual wine version in combination with the exiles.exe
2. Problems within the logic checking if there are new updates
3. failure within your local installation

**Comment by alinmear** [comment]
Ping!

**Comment by alinmear** [comment]
@drphlux any news on this issue?

**Comment by alinmear** [comment]
Closing this issue due author is not responding. Can't reproduce the described behavior.
