### ISSUE TITLE
Public server

### ISSUE THREAD

**Issue by cgarnier** [alinmear/docker-conanexiles#2]
Hey,
I cant find how to make the server public. 
Do you know a to do it ?

**Comment by alinmear** [comment]
Hello @cgarnier, normaly when the ports have been opened the server should be registered (queryport). What makes you think, that your server isn't public? 

Can you find your server listed here: https://topconanservers.com/

**Comment by alinmear** [comment]
@cgarnier Does it work for you?

**Comment by cgarnier** [comment]
Yes, in fact my server was public but it was just not instant =)
There is something weird in the server list. It seeams that some server are faking there real ping. Do you know how they do?
For exemple i can see some server with 10ms less then possible.
