### ISSUE TITLE
Update WINE Repository

### ISSUE THREAD

**Issue by alinmear** [alinmear/docker-conanexiles#20]
!!! PLEASE NOTE THAT THIS REPOSITORY IS DEPRECATED !!!

For more information, please see:

    https://www.winehq.org/pipermail/wine-devel/2017-March/117104.html

The following commands can be used to add the new repository:

    wget https://dl.winehq.org/wine-builds/Release.key
    sudo apt-key add Release.key
    sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'

 More info: https://launchpad.net/~wine/+archive/ubuntu/wine-builds

**Comment by drphlux** [comment]
Latest ubuntu (LTS) even has wine3 repo included. Maybe upgrade the docker source image to: ubuntu:18.04 ?
Ref: https://linuxconfig.org/install-wine-on-ubuntu-18-04-bionic-beaver-linux

**Comment by alinmear** [comment]
Revamp should solve problems
