### ISSUE TITLE
directory mapping for settings files

### ISSUE THREAD

**Issue by Hr46ph** [alinmear/docker-conanexiles#24]
Just something I don't understand so I figured I'd ask.

Why didn't you opt to map the directory with all the ini files to a local mountpoint like so:

-v /path/to/inis/in_container:/mnt/data/conan_inis

If its permissions, those can be easily fixed.

Thanks.

**Comment by alinmear** [comment]
I think this heavily depends on your container setup, provisioning and backup strategy.

**Comment by Hr46ph** [comment]
Docker-compose is new for me, I had made a mistake in that yml file. Basically, your last example maps it to a dir on the host which is the same as the -v option on the command line. That's what I wanted :).

Thanks!
