### ISSUE TITLE
mod support

### ISSUE THREAD

**Issue by Hr46ph** [alinmear/docker-conanexiles#25]
Hi,

Sorry but is there any mod support or any instructions on how I can get mods working on the server?

Thanks!

**Comment by alinmear** [comment]
Just googled it myself.

1. Download a mod (e.g. steamworkshop)
2. Locate the Mod Folder locally 
- <Local Steam Lib Folder>/Conan Exiles/ConanSandbox/Mods/modlist.txt
- Open the file and check local place of mods
3. Upload/Copy into Server Mod Folder /ConanSandbox/Mods (.pak files)
4. Activate Mods via modlist.txt
- e.g. ItemStack.pak

**Comment by Hr46ph** [comment]
Thanks, I found that too but the problem had to do with the docker-compose file, a mistake in there had the conan-exiles directory in the container only and not mapped to a persistent volume accessible from the host.

Now that is fixed, I can start adding mods.

Thanks again!
