### ISSUE TITLE
mod support

### ISSUE THREAD

**Issue by acelan** [alinmear/docker-conanexiles#26]
Are you planning to add mod downloading/updating in the script?

**Comment by sudzwerg** [comment]
Yeah Mods would be nice to have

**Comment by acelan** [comment]
I've created one and didn't consider any slave servers situation.
So, I'm not sure if I should create a pull request.
Please help to review it and let me know what else I should do to submit it back.
https://github.com/acelan/docker-conanexiles/tree/mod_support

**Comment by thiphariel** [comment]
@acelan I currently try your fork to enable some mods but without success. I only have to put some IDS on the mod_list.txt file or I have something else to do ?

**Comment by Andargor** [comment]
I haven't tried your fork, but manually this can be done this way in case anyone wonders:

```bash
docker exec -it conanexiles bash
```

Inside the container:

```bash
/steamcmd/steamcmd.sh +login anonymous +workshop_download_item 440900 864199675 +quit
cp /root/Steam/steamapps/workshop/content/440900/864199675/Pickup+.pak /conanexiles/ConanSandbox/Mods/
supervisorctl restart conanexilesServer
```

**Comment by alinmear** [comment]
Mod Support has been merge due #40. Closing this issue

**Comment by Thoughtscape2014** [comment]
Hi Alinmear, not sure if you are still monitoring this as it has been closed but does the latest [master] have mod support aswell as 

>       - "CONANEXILES_Game_DiscordPlugin_Token=[DISCORD TOKEN]"                               
>       - "CONANEXILES_Game_DiscordPlugin_Channel=[DISCORD CHANNEL ID]"    

functionality?

Regards,

Mick.

**Comment by acelan** [comment]
These discord settings are not related to mod support, and I don't think discord support has been integrated.
So, these settings could be ignored or removed.
