### ISSUE TITLE
Feature-Request: Variable Update-Timer

### ISSUE THREAD

**Issue by jammsen** [alinmear/docker-conanexiles#36]
Hey @alinmear ,
first of, love your work, its awesome, thanks a lot!

As a feature request, i would love to see an environment variable in the Dockerfile, maybe something similar like CONANEXILES_Update_Timer=15 so its possible to set the update-interval down from 15minutes to like 3 or so. 

At the moment its static in the conanexiles_controller (Bash) in the update function on line 116 and in the rcon-cli its like semi static on line 58 def shutdown (my Pyhton is basically non existent sorry for that) as far as i understand. Also the readme.MD might need a change.

Do you thing we can do that?

**Comment by alinmear** [comment]
Hi @jammsen. I will take a look at it.

**Comment by alinmear** [comment]
I added the new env Variable CONANEXILES_UPDATE_SHUTDOWN_TIMER

**Comment by jammsen** [comment]
Thank you!
