### ISSUE TITLE
Wine stuck waiting at wine-mono install prompt

### ISSUE THREAD

**Issue by sPOiDar** [alinmear/docker-conanexiles#48]
Connecting via VNC shows wine is stuck at the prompt to install wine-mono, preventing the server from starting up successfully. If Mono is not required, it may be possible to add an override to avoid the prompt, otherwise a global mono install may need to be added to the image.

ETA: The server does eventually start, this just appears to add some delay.

**Comment by alinmear** [comment]
Merged update from @Flow86. Thank you for your work
