### ISSUE TITLE
Env not added to settings

### ISSUE THREAD

**Issue by boiss007** [alinmear/docker-conanexiles#50]
Hello,
First, thanks for the cool docker. i have used it for some time, but on a server reinstall, i started my usual docker-compose and no Env where added to setting. Specifically, the "AdminPassword and "ServerPassword" where not in my .ini.
So free login to the server, no access to the server config and worst of all, no nudity...! I modified the .ini directly and all is well but the Environnment Variables config from docker-compose seems to be broken.

**Comment by D3RFLO** [comment]
Hey, i don't know if you still need this but i might have found the solution:

In the docker-compose.yml remove the env variable:  - "CONANEXILES_INSTANCENAME=exiles0" then it worked for me

**Comment by h4llm3n** [comment]
> Hey, i don't know if you still need this but i might have found the solution:
> 
> In the docker-compose.yml remove the env variable: - "CONANEXILES_INSTANCENAME=exiles0" then it worked for me

Thanks, that worked for me. 👍

**Comment by jcoker85** [comment]
I think this is a bug in entrypoint.sh:

# Check if instance nanme given
    [ -n "${CONANEXILES_INSTANCENAME}" ] && _config_folder="/conanexiles/ConanSandbox/Saved/${CONANEXILES_INSTANCENAME}/Config/WindowsServer"

I think the path should be 

/conanexiles/ConanSandbox/${CONANEXILES_INSTANCENAME}/Saved/Config/WindowsServer

If you look after the container is done being created, the modified files are in the wrong location as listed by the first path, and do not correctly overwrite the ones in the second path, which is what the server uses.

**Comment by alinmear** [comment]
Fixed in Master. Now Env Variables are setup again correctly
