### ISSUE TITLE
Server not showing in servers list

### ISSUE THREAD

**Issue by Dancia** [alinmear/docker-conanexiles#52]
I am able to connect to server via "Direct Connect" (external IP), but the server never appears in "Servers List". Is this normal behavior?

**Comment by h4llm3n** [comment]
Do you find it via Steam server browser? Maybe it's the wrong name?

**Comment by alinmear** [comment]
This happend because of a bug within the entrypoint script. Env Variables where not provisioned to instance config. Fixed within master
